[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
gas_reports = ["*"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200

[profile.remappings]
"@openzeppelin/" = "lib/openzeppelin-contracts/"

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
